### ISSUE TITLE
Failed prop type: Invalid prop `children` supplied to `ForwardRef(ButtonGroup)`, expected a ReactNode.

### ISSUE THREAD

**Issue by izszzz** [izszzz/tunescore#179]
arning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(ButtonGroup)`, expected a ReactNode.
    at ButtonGroup (webpack-internal:///./node_modules/@mui/material/ButtonGroup/ButtonGroup.js:139:83)
    at ScoreButtonGroup (webpack-internal:///./src/components/elements/button/group/score.tsx:22:23)
    at ActionButton (webpack-internal:///./src/pages/musics/[id]/index.tsx:202:22)

**Comment by izszzz** [comment]
`https://github.com/mui/material-ui/issues/34415`

**Comment by izszzz** [comment]
保留
